[book]
authors = ["rumpelst1lzk1n"]
language = "de"
multilingual = false
src = "src"
title = "Einsteigerguide FPV"
description = "Orientierungshilfe f√ºr Einsteiger in das Thema 'FPV' mit Multikoptern (aka 'Drohnen')"

[output.wordcount]
optional = true

[output.html]
base-url = "https://rumpelst1lzk1n.github.io"
git-repository-url = "https://github.com/rumpelst1lzk1n/rumpelst1lzk1n.github.io"

[output.html.fold]
enable = true
level = 1
